### PR TITLE
1154 integrator is handled as adaptive if using small fixed step sizes

### LINKED ISSUE #1154: Integrator is handled as adaptive if using small fixed step sizes
### Motivation / Current Behaviour

When calculating with a small but fixed step size, it can happen that the variable m_is_adaptive is set to true in the integrator, although no adaptive method is used. (I used a step size of 10^-2 and a high tmax).

### Enhancement description

It is sufficient to insert a tolerance in the calculation of m_is_adaptive.

### Additional context

_No response_

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Added tolerance in the calculation of m_is_adaptive.
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1154

### CODE REVIEW

File: cpp/memilio/config.h [hunk 1]
```diff
@@ -27,6 +27,7 @@
 
 #include "memilio/config_internal.h"
 #include <type_traits>
+#include "ad/ad.hpp"
 
 using ScalarType = double;
```
Comment (reneSchm) [inline cpp/memilio/config.h:33]: Since we don't use any properties of the ad type we should get away with only a forward declaration. This way we avoid including the ad header in basically all files (because config.h is), which may reduce compilation time or binary size.

```suggestion

using ScalarType = double;

namespace ad
{
namespace internal
{
// Forward declaration used for support of ad types in Limits.
template <class AD_TAPE_REAL, class DATA_HANDLER>
struct active_type;
} // namespace internal
} // namespace ad
```

File: cpp/memilio/config.h [hunk 2]
```diff
@@ -67,6 +68,15 @@ struct Limits<double> {
         return 1e-12;
     }
 };
+
+template <class AD_TAPE_REAL, class DATA_HANDLER>
+struct Limits<ad::internal::active_type<AD_TAPE_REAL, DATA_HANDLER>> {
+    /// @brief Returns the limit under which an ad::internal::active_type may be rounded down to zero.
```
Comment (reneSchm) [inline cpp/memilio/config.h:74]: I think using "AD values" or "AD value_type" instead of the internal name is more helpful in the documentation.

I am also a bit torn on the template names. As is, it is easy to find their original use and/or documentation, but they technically do not conform to our coding guidelines. I slightly lean to the conforming option, maybe use "AdReal" (or "AdTapeReal") and "DataHandler"?

**Review by reneSchm — CHANGES_REQUESTED** [review]

File: cpp/memilio/config.h (hunk 1 above)
Comment (lenaploetzke) [reply cpp/memilio/config.h:33]: That is a very good point, thank you!

File: cpp/memilio/config.h (hunk 2 above)
Comment (lenaploetzke) [reply cpp/memilio/config.h:74]: Yes ok, I will adapt this to be in accordance with our guidelines.

**Comment by lenaploetzke** [comment]
I don't know what the problem is with codecov again.
