### PR TITLE
898 change test for valid transition distibution from ide model

### LINKED ISSUE #898: Change test for valid transition distibution from ide model
### Motivation / Current Behaviour

Currently, the unused TransitionDistribution S->E is tested for validity, which can cause unexpected errors.

### Enhancement description

Remove Test of this TransitionDistribution.

### Additional context

Code can be copied from #771: cpp/models/ide_secir/parameters.h

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Changed the index of a test in check_constraints for the ide model because the transitiondistribution S-> E is never used, so it does not have to have valid support. This can lead to unexpected errors if the function was set arbitrarily.

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #898

### CODE REVIEW

File: cpp/models/ide_secir/parameters.h [hunk 1]
```diff
@@ -270,9 +270,9 @@ class Parameters : public ParametersBase
             return true;
         }
 
-        for (size_t i = 0; i < (int)InfectionTransition::Count; i++) {
+        for (size_t i = 1; i < (int)InfectionTransition::Count; i++) {
```
Comment (annawendler) [inline cpp/models/ide_secir/parameters.h:273]: A comment would be helpful to understand why not all TransitionDistributions are checked.

**Review by annawendler — CHANGES_REQUESTED** [review]
Looks good, please add one comment :)

**Review by annawendler — APPROVED** [review]
