### PR TITLE
950 build cpp msvc debug latest fails at the main branch

### LINKED ISSUE #950: build-cpp-msvc (Debug, latest) fails at the main branch
### Bug description

CI has been failing for two days because of a new version of msvc. The warning should be suppressed.

### Version

Github (CI, Actions, etc.)

### To reproduce

Run CI

### Relevant log output

```zsh
D:\a\memilio\memilio\cpp\build-win\_deps\spdlog-src\include\spdlog/fmt/bundled/format.h(490): error C2220: the following warning is treated as an error
D:\a\memilio\memilio\cpp\build-win\_deps\spdlog-src\include\spdlog/fmt/bundled/format.h(490): warning C4996: 'stdext::checked_array_iterator<T*>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
```

### Add any relevant information, e.g. used compiler, screenshots.

_No response_

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #950.

### CODE REVIEW

File: cpp/memilio/utils/logging.h [hunk 1]
```diff
@@ -27,7 +27,11 @@
 #endif
 
 #include "memilio/utils/compiler_diagnostics.h"
+
+// C4996: Some stdext functions will be removed in the future and are used in spdlog. Maybe a future version of spdlog will fix this.
```
Comment (reneSchm) [inline cpp/memilio/utils/logging.h:31]:
```suggestion
// C4996: Some stdext functions used in spdlog 1.11 are marked as deprecated in version 19.38.33135.0 of MSVC. Maybe a future version of spdlog will fix this.
```

**Review by reneSchm — CHANGES_REQUESTED** [review]
Nice fix. I'd add the relevant version numbers for future reference

**Review by reneSchm — APPROVED** [review]
