### PR TITLE
1185 wrong index in ode seir model

### LINKED ISSUE #1185: Wrong index in ODE_SEIR model
### Bug description

In [https://github.com/SciCompMod/memilio/blob/main/cpp/models/ode_seir/model.h#L83](https://github.com/SciCompMod/memilio/blob/main/cpp/models/ode_seir/model.h#L83) the index `j` instead of `i` should be used.

### Version

Any

### To reproduce

Run an ODE_SEIR model with more than one age group.

### Relevant log output

_No response_

### Add any relevant information, e.g. used compiler, screenshots.

_No response_

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by kilianvolmer**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Fixed wrong index in `model.h` of ODE SEIR model
- Added test to `test_odeseir.cpp` that would have failed with the previous wrong index

If need be, add additional information and what the reviewer should look out for in particular:

Closes #1185 .

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

### CODE REVIEW

File: cpp/tests/test_odeseir.cpp [hunk 1]
```diff
@@ -362,6 +362,49 @@ TEST(TestSeir, get_flows)
...
+    model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Infected}]  = 10;
+    model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Recovered}] = 10;
+    model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Susceptible}] =
+        total_second_population - model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Exposed}] -
+        model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Infected}] -
+        model.populations[{mio::AgeGroup(1), mio::oseir::InfectionState::Recovered}];
+
+    model.parameters.set<mio::oseir::TimeExposed<double>>(2);
+    model.parameters.set<mio::oseir::TimeInfected<double>>(4);
+    model.parameters.set<mio::oseir::TransmissionProbabilityOnContact<double>>(1);
```
Comment (HenrZu) [inline cpp/tests/test_odeseir.cpp:389]: These params should be set age specific.
just use a simple for loop.

**Review by HenrZu — CHANGES_REQUESTED** [review]
Thank you for findings this typo. Just one short comment. Then we can merge this :)

File: cpp/tests/test_odeseir.cpp (hunk 1 above)
Comment (HenrZu) [reply cpp/tests/test_odeseir.cpp:389]: also, u can add the correct number of susceptibles using the  `set_difference_from_group_total `function as shown in https://github.com/SciCompMod/memilio/blob/8958e3159c7cdb64265f93f21d025f76d33a91c0/cpp/examples/ode_seir_ageres.cpp#L50

File: cpp/tests/test_odeseir.cpp [hunk 2]
```diff
@@ -362,6 +362,48 @@ TEST(TestSeir, get_flows)
...
+
+    for (auto i = mio::AgeGroup(0); i <= mio::AgeGroup(1); i++) {
+        model.parameters.get<mio::oseir::TimeExposed<double>>()[i]                      = 2;
+        model.parameters.get<mio::oseir::TimeInfected<double>>()[i]                     = 4;
+        model.parameters.get<mio::oseir::TransmissionProbabilityOnContact<double>>()[i] = 1;
+    }
+
+    mio::ContactMatrixGroup& contact_matrix =
+        model.parameters.get<mio::oseir::ContactPatterns<double>>().get_cont_freq_mat();
+    contact_matrix[0].get_baseline().setConstant(1);
```
Comment (HenrZu) [inline cpp/tests/test_odeseir.cpp:391]: The contact matrix should be done with (see ode_secir_ageres.cpp)
```
mio::ContactMatrixGroup& contact_matrix = params.get<mio::osecir::ContactPatterns<double>>();
contact_matrix[0] =
        mio::ContactMatrix(Eigen::MatrixXd::Constant((size_t)nb_groups, (size_t)nb_groups, fact * cont_freq));
```

**Review by HenrZu — CHANGES_REQUESTED** [review]
Thank you. One last comment :)  Then we can merge this PR

**Review by HenrZu — APPROVED** [review]
