### PR TITLE
965 use int instead of unsigned int in lct infection state

### LINKED ISSUE #965: Use int instead of unsigned int in LCT infection state
### Motivation / Current Behaviour

Currently LctInfectionState uses unsigned ints as template parameters and as return values of the functions. This leads to some hard to detect unexpected behaviour when using the return values in calculations, especially when multiplying them with negative values.

### Enhancement description

Replace unsigned int with int and include some static assert statements to ensure that the parameters are non-negative.
Also update all the explicit type conversions. This change should simplify some calculations and make them less error-prone

### Additional context

_No response_

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Ints instead of unsigned ints are now used in the LctInfectionState class.
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #965

### CODE REVIEW

File: cpp/memilio/epidemiology/lct_infection_state.h [hunk 1]
```diff
@@ -31,12 +31,12 @@ namespace mio
...
  *      The number of given template arguments must be equal to the entry Count from InfectionState.
  */
-template <class InfectionStates, unsigned int... Ns>
+template <class InfectionStates, int... Ns>
 class LctInfectionState
 {
 public:
     using InfectionState = InfectionStates;
-    static_assert((unsigned int)InfectionState::Count == sizeof...(Ns),
+    static_assert((int)InfectionState::Count == sizeof...(Ns),
```
Comment (reneSchm) [inline cpp/memilio/epidemiology/lct_infection_state.h:39]: sizeof returns a size_t, so you should not cast to int here
```suggestion
    static_assert((size_t)InfectionState::Count == sizeof...(Ns),
```

File: cpp/examples/lct_secir.cpp [hunk 2]
```diff
@@ -47,25 +47,25 @@ int main()
                                                                 {50},  {10, 10, 5, 3, 2}, {20},         {10}};
 
     // Assert that initial_populations has the right shape.
-    if (initial_populations.size() != (int)LctState::InfectionState::Count) {
+    if ((int)initial_populations.size() != (int)LctState::InfectionState::Count) {
```
Comment (reneSchm) [inline cpp/examples/lct_secir.cpp:50]:
```suggestion
    if (initial_populations.size() != (size_t)LctState::InfectionState::Count) {
```
Try to avoid narrowing if neither value is an int.

File: cpp/examples/lct_secir.cpp [hunk 3]
```diff
@@ -47,25 +47,25 @@ int main()
...
         mio::log_error("The number of vectors in initial_populations does not match the number of InfectionStates.");
         return 1;
     }
-    if ((initial_populations[(int)LctState::InfectionState::Susceptible].size() !=
+    if (((int)initial_populations[(int)LctState::InfectionState::Susceptible].size() !=
          LctState::get_num_subcompartments<LctState::InfectionState::Susceptible>()) ||
```
Comment (reneSchm) [inline cpp/examples/lct_secir.cpp:55]: Here the narrowing is probably correct. You could cast to size_t if you want to assume/guarantee that `get_num_subcompartments` is non-negative.

File: cpp/memilio/epidemiology/lct_infection_state.h [hunk 4]
```diff
@@ -49,7 +49,7 @@ class LctInfectionState
      * @return Number of subcompartments for State.
      */
     template <InfectionState State>
-    static constexpr unsigned int get_num_subcompartments()
+    static constexpr int get_num_subcompartments()
```
Comment (reneSchm) [inline cpp/memilio/epidemiology/lct_infection_state.h:52]: Since the return values can now be negative, please add to the documentation whether negative values can be returned.

File: cpp/memilio/epidemiology/lct_infection_state.h [hunk 5]
```diff
@@ -64,20 +64,20 @@ class LctInfectionState
      * @return Index of the first subcompartment for a vector with one entry per subcompartment.
      */
     template <InfectionState State>
-    static constexpr unsigned int get_first_index()
+    static constexpr int get_first_index()
```
Comment (reneSchm) [inline cpp/memilio/epidemiology/lct_infection_state.h:67]: See comment on l52 / get_num_subcompartments

**Review by reneSchm — CHANGES_REQUESTED** [review]
Looks good, but please check that all `Ns` are positive (non-negative?) - I think there is an assert for that, but please make sure.

**Comment by lenaploetzke** [comment]
> Looks good, but please check that all `Ns` are positive (non-negative?) - I think there is an assert for that, but please make sure.

Yes there was already a `static_assert(((Ns > 0) && ...),)` thing in line 43 of lct_infection_state.h for that because we actually need that the Ns are at least one.

**Review by reneSchm — APPROVED** [review]
Neat.
