### PR TITLE
1034 ide model simulation does not work under some conditions

### LINKED ISSUE #1034: IDE model simulation does not work under some conditions
### Motivation / Current Behaviour

Currently, we have that in the function compute_compartment_from_flows(), the idx_TransitionDistribution2 is set to 0 if not stated otherwise. On the other hand, it is not necessary nor specified in the check_constraints() function that the TransitionDistribution for SusceptibleToExposed is a StateAgeFunction of Type b).
For example, if you use ConstantFunction for TransitionDistribution[0], the simulation will not work properly because the maximum support of the ConstantFunction is used. 

### Enhancement description

A quick fix should be to include an if clause for the calculation of calc_time in compute_compartment_from_flows().

### Additional context

_No response_

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- compute_compartment_from_flows() now works when the TransitionDistribution SusceptibleToExposed is set to a ConstantFunction (or any other function with an invalid maximum support).
- fixed missing space in error message

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1034.

### CODE REVIEW

File: cpp/models/ide_secir/model.cpp [hunk 1]
```diff
@@ -60,12 +60,17 @@ void Model::compute_compartment_from_flows(ScalarType dt, Eigen::Index idx_Infec
...
 {
-    ScalarType sum = 0;
-
+    ScalarType sum       = 0;
+    ScalarType calc_time = 0;
     // Determine relevant calculation area and corresponding index.
-    ScalarType calc_time =
-        std::max(parameters.get<TransitionDistributions>()[idx_TransitionDistribution1].get_support_max(dt, m_tol),
-                 parameters.get<TransitionDistributions>()[idx_TransitionDistribution2].get_support_max(dt, m_tol));
+    if ((1 - parameters.get<TransitionProbabilities>()[idx_TransitionDistribution1]) > 0) {
```
Comment (annawendler) [inline cpp/models/ide_secir/model.cpp:66]:
```suggestion
    if ((parameters.get<TransitionProbabilities>()[idx_TransitionDistribution2]) > 0) {
```
I find that a bit more intuitive but don't have a strong opinion here.

Comment (lenaploetzke) [reply cpp/models/ide_secir/model.cpp:66]: That is actually wrong because idx_TransitionDistribution2 can be a random index if the second distribution is not used (eg for E->C). This is the whole problem of this issue/PR. 

I used 1- prob[idx]>0 because this is the factor used in the calculation below, another opportunity would of course be prob[idx1]<1.

Comment (annawendler) [reply cpp/models/ide_secir/model.cpp:66]: But if the second TransitionDistribution is not used the default index is 0 and for this the probability is 1. But maybe I'm confused here.

But it does make sense to use the first Transition Distribution in the if statement because this already determines if we need both distributions or not, so it is fine as it is.

**Review by annawendler — APPROVED** [review]

File: cpp/models/ide_secir/model.cpp (hunk 1 above)
Comment (lenaploetzke) [reply cpp/models/ide_secir/model.cpp:66]: Yes you are right, we actually have a test that ensures that this probability is one. :) I still prefer the other solution.
