### PR TITLE
1382 Fix incorrect overload detection and type mismatch in `test_commuters`

### LINKED ISSUE #1382: examples/ode_secir_graph.cpp does not use test_commuters overload
### Bug description

**Description:**  
While running the `ode_secir_graph.cpp` example, the `test_commuters` logic is not executed correctly. Instead, the fallback (empty) overload of `test_commuters` is always chosen.  

**Details:**  
- The intended overload `test_commuters(FP, Simulation<FP, Model<FP>>&, Eigen::Ref<Eigen::VectorX<FP>>, FP)` is not found by the metaprogramming detection in `test_commuters_expr_t`.  
- As a result, commuter testing (reassignment of detected commuters into separate compartments) is skipped in the example.  
- Debug output confirms that execution always falls back to the empty implementation with:  
  ```cpp
  std::enable_if_t<!is_expression_valid<test_commuters_expr_t, Sim>::value, void*> = nullptr
  ```

**Impact:** 
The mobility simulation runs without applying commuter detection.

### Version

Linux

### To reproduce

./../build/bin/ode_secir_graph_example

### Relevant log output

```zsh

```

### Add any relevant information, e.g. used compiler, screenshots.

```zsh

```

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

### LINKED ISSUE #1383: Type mismatch in metaprogramming for test_commuters
### Bug description

There is a type mismatch in the metaprogramming expression used for `test_commuters`.

In [`[metapopulation_mobility_instant.h](https://github.com/SciCompMod/memilio/blob/main/cpp/memilio/mobility/metapopulation_mobility_instant.h#L542-L545)`](https://github.com/SciCompMod/memilio/blob/main/cpp/memilio/mobility/metapopulation_mobility_instant.h#L542-L545), the alias is defined as:

```cpp
template <typename FP, class Sim>
using test_commuters_expr_t = decltype(test_commuters(
    std::declval<Sim&>(), std::declval<Eigen::Ref<const Eigen::VectorX<FP>>&>(), std::declval<FP>()));
```

Here the second argument is declared as
`Eigen::Ref<const Eigen::VectorX<FP>>&`.

However, in [`[ode_secir/model.h](https://github.com/SciCompMod/memilio/blob/main/cpp/models/ode_secir/model.h#L692-L693)`](https://github.com/SciCompMod/memilio/blob/main/cpp/models/ode_secir/model.h#L692-L693), `test_commuters` is actually implemented as:

```cpp
template <typename FP, class Base = mio::Simulation<Model<FP>, FP>>
auto test_commuters(Simulation<FP, Base>& sim, Eigen::Ref<Eigen::VectorX<FP>> mobile_population, FP time)
{
    ...
}
```

So the function expects a **non-const** `Eigen::Ref<Eigen::VectorX<FP>>`, while the metaprogramming code uses a `const` reference.
This causes a mismatch and should be fixed by removing the `const` in the alias.

Additionally, the template parameter `Base` in the definition of `test_commuters` should be updated.
It currently uses:

```cpp
class Base = mio::Simulation<Model<FP>, FP>
```

but the correct order should be:

```cpp
class Base = mio::Simulation<FP, Model<FP>>
```

### Summary of fixes

* In `test_commuters_expr_t`, change
  `Eigen::Ref<const Eigen::VectorX<FP>>&` → `Eigen::Ref<Eigen::VectorX<FP>>`.
* In the `test_commuters` template, change
  `class Base = mio::Simulation<Model<FP>, FP>` → `class Base = mio::Simulation<FP, Model<FP>>`.

### Version

Windows

### To reproduce

./../build/bin/ode_secir_graph_example

### Relevant log output

```zsh

```

### Add any relevant information, e.g. used compiler, screenshots.

```zsh

```

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

### LINKED ISSUE #1384: Missing template parameter FP in the metaprogramming validation
### Bug description

There is a missing template parameter `FP` in the metaprogramming validation for `test_commuters_expr_t` and others.

We correctly defined the alias with `FP` in

```cpp
template <typename FP, class Sim>
using test_commuters_expr_t =
    decltype(test_commuters(std::declval<Sim&>(), std::declval<Eigen::Ref<Eigen::VectorX<FP>>>(), std::declval<FP>()));
```

However, when using it in the validation, we currently write:

```cpp
is_expression_valid<test_commuters_expr_t, Sim>::value
```

This omits the `FP` template parameter.
It should instead be:

```cpp
is_expression_valid<test_commuters_expr_t, FP, Sim>::value
```

### Summary of fix

* Add the missing `FP` parameter when checking `is_expression_valid` for `test_commuters_expr_t`.

### Version

Windows

### To reproduce

./../build/bin/ode_secir_graph_example

### Relevant log output

```zsh

```

### Add any relevant information, e.g. used compiler, screenshots.

```zsh

```

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

### PR DESCRIPTION
**Pull request by julianlitz**
# Changes and Information

This PR fixes several issues preventing the correct `test_commuters` overload from being selected.

- **Fix #1382:** The fallback empty `test_commuters` implementation was always selected.  
- **Fix #1383:** Removed `const` from `Eigen::Ref<const Eigen::VectorX<FP>>` in `test_commuters_expr_t` and corrected the default template parameter to `mio::Simulation<FP, Model<FP>>`.  
- **Fix #1384:** Added missing `FP` template parameter to `is_expression_valid<test_commuters_expr_t, FP, Sim>::value`.

After these changes, the correct overload is now detected and executed. Verified with `ode_secir_graph.cpp` where commuter testing runs as intended.

## Merge Request - Guideline Checklist

Please check our [git workflow](https://memilio.readthedocs.io/en/latest/development.html#git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://memilio.readthedocs.io/en/latest/development.html#coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation within the code** (Doxygen) for new functionality has been added in the code
- [ ] Appropriate **external documentation** (ReadTheDocs) for new functionality has been added to the online documentation
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://memilio.readthedocs.io/en/latest/development.html#agent-based-model-development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1382, #1383, #1384

### CODE REVIEW

File: cpp/memilio/mobility/metapopulation_mobility_instant.h [hunk 1]
```diff
@@ -523,26 +522,26 @@ using get_mobility_factors_expr_t = decltype(get_mobility_factors(
...
-          std::enable_if_t<!is_expression_valid<get_mobility_factors_expr_t, Sim>::value, void*> = nullptr>
-auto get_mobility_factors(const SimulationNode<FP, Sim>& /*node*/, FP /*t*/,
-                          const Eigen::Ref<const Eigen::VectorX<FP>>& y)
-{
-    return Eigen::VectorX<FP>::Ones(y.rows());
-}
-template <typename FP, class Sim,
-          std::enable_if_t<is_expression_valid<get_mobility_factors_expr_t, Sim>::value, void*> = nullptr>
+template <typename FP, class Sim>
 auto get_mobility_factors(const SimulationNode<FP, Sim>& node, FP t, const Eigen::Ref<const Eigen::VectorX<FP>>& y)
```
Comment (reneSchm) [inline cpp/memilio/mobility/metapopulation_mobility_instant.h]: Do you want to replace the `const Eigen::Ref<const Eigen::VectorX<FP>>&` by `Eigen::Ref<Eigen::VectorX<FP>>`?

Comment (julianlitz) [reply cpp/memilio/mobility/metapopulation_mobility_instant.h]: I don't think there is a mismatch left which can cause issues right?

If `Eigen::Ref<const Eigen::VectorX<FP>> const&`

is used correctly across all the configurations, I don't mind it.

Comment (julianlitz) [reply cpp/memilio/mobility/metapopulation_mobility_instant.h]: image
But they even use it like this on their website? I don't understand why you think this would be illegal.
To me Eigen::Ref is just a type that acts like a reference, but we can mark it as const& if we wish to as well.
